application: cookmom-app
version: 1
runtime: python
api_version: 1
#default_expiration: "30d"

handlers:
- url: /secret_remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /media
#  expiration: "365d"
  static_dir: _generated_media

- url: /favicon.ico
  expiration: "365d"
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /html
  static_dir: static

- url: /.*
  script: main.py
  

