application: cookmom-app
version: dev-2
runtime: python
api_version: 1
#default_expiration: "30d"

handlers:
- url: /cookmom_remote_api_private
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /media
#  expiration: "365d"
  static_dir: _generated_media

- url: /fbconnect
  static_dir: media/fbconnect
  
- url: /favicon.ico
  expiration: "365d"
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /html
  static_dir: static
  
- url: /stats.*
  script: appstats/ui.py

- url: /.*
  script: bootstrap.py
  

